[package]
name = "rotascope-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
image = "0.24"
x11rb = "0.10" # Linux 屏幕捕获
windows = "0.48" # Windows API
env_logger = "0.10"
log = "0.4"
rotascope-core = {path = "../rotascope-core"}
tokio-util = { version = "0.7.17", features = ["codec"] }
futures = "0.3"
[profile.release]

opt-level = "z"
codegen-units = 1